spring:
  application:
    name: practice-data-structure
server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: order-streams-app